name: Deploy Backend

on:
  push:
    branches: [cd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/github-runner/l2p-backend
            git reset --hard HEAD
            git checkout cd
            git pull origin cd
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker-compose run --rm app alembic upgrade head
            docker image prune -f
            echo "âœ… Backend deployed successfully!"
            docker-compose ps
